### ISSUE TITLE
Error - input array

### ISSUE THREAD

**Issue by alberto98fx** [rmislam/PythonSIFT#14]
I'm getting this error with two pictures I used: 

```
Traceback (most recent call last):
  File "template_matching_demo.py", line 55, in <module>
    newimg[hdif:hdif + h1, :w1, i] = img1
ValueError: could not broadcast input array from shape (1280,960) into shape (0,960)
```
It seems like it couldn't fit some points into the other picture, I suspect the issue is caused by different size: 

img1 is `960 × 1280` while img2 is `1080 × 720`.

**Comment by alberto98fx** [comment]
Update: 

I can confirm, perhaps there should be a warning of some kind or deal with the images and scale down in case the target image is smaller than the source? 

I inverted the pictures and works just fine!

**Comment by rmislam** [comment]
Hi @alberto98fx, can you please attach the two images you used? I want to reproduce and confirm the issue.

**Comment by rmislam** [comment]
@alberto98fx  I can't reproduce this, and since I haven't heard from you, I'll close this issue. Feel free to reopen it later if you can provide me your two images.
