### ISSUE TITLE
How to find the coordinates of the corresponding points among the matching points of two graphs

### ISSUE THREAD

**Issue by yichanshiwoa** [rmislam/PythonSIFT#16]
thank for your research,i meet a problem when i want to get the coordinates of the correspondence point.there are too many point to find the corresponding point.thanks sincerely.

**Comment by rmislam** [comment]
HI @yichanshiwoa, inside the demo script `template_matching_demo.py`, on lines 32 and 33 you can see two variables: `src_pts` and `dst_pts`. These are the coordinates of the corresponding points.

Does this answer your question? I'm not sure what you mean when you say "there are too many points to find the corresponding points".

**Comment by yichanshiwoa** [comment]
incerely thank you for your reply. I mean, how do you find the number of each pair of matching points, for example, if the matching point number 1 on the left is the matching point number 2 on the right, how do you find that number. My goal is to find the pixel value of each pair of matching points.

**Comment by yichanshiwoa** [comment]
Sincerely thank you for your reply. I mean, how do you find the number of each pair of matching points, for example, if the matching point number 1 on the left is the matching point number 2 on the right, how do you find that number. My goal is to find the pixel value of each pair of matching points.

**Comment by yichanshiwoa** [comment]
Hi，thank your advice, i have solved this questions.
