### ISSUE TITLE
edgeThreshold

### ISSUE THREAD

**Issue by wendy127green** [rmislam/PythonSIFT#18]
Hello, thank you for the share.
Is the edge threshold considered in the program? I did not find it, neither hessian matrix for edge effect elimination.

**Comment by rmislam** [comment]
Yes, we are definitely using edge thresholding. In `pysift.py` see the `computeHessianAtCenterPixel` function -- there's your Hessian matrix. The tutorial provides explanation if needed. Everything mentioned in the original SIFT paper is implemented in this repo.

**Comment by wendy127green** [comment]
@rmislam Ok, thanks
