### ISSUE TITLE
Deprecated implementation

### ISSUE THREAD

**Issue by ra0e** [rmislam/PythonSIFT#20]
PythonSIFT/pysift.py:80: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(gaussian_images)

**Comment by rmislam** [comment]
@ra0e
Fixed in commit `78c779ae58fd95d4ea65924fd7471d8038f5a9be`.
Thanks for pointing this out.
