### ISSUE TITLE
Possible bug with pip instalation

### ISSUE THREAD

**Issue by Zenos-Paradox** [rmislam/PythonSIFT#23]
Hi,

First of all, I love what you are doing. This is exactly what my class (and EVERY other source I've found) is missing; actual aplication of the theory.

That said, after installing via pip I tryed to run a test code:
```
import cv2
import pysift

image = cv2.imread('your_image.png', 0)
keypoints, descriptors = pysift.computeKeypointsAndDescriptors(image)

```

and got the following error: `ModuleNotFoundError: No module named 'urlparse'`

I suppose it's got to do with [this thread](https://stackoverflow.com/questions/50146520/no-module-named-urlparse-but-im-not-using-urlparse) In which it's explaind that urlparse implementation was changed between Python 2 and 3. I tryed to re install pysift directly from github but I'm not very experienced with that an simply running `pip install git+https://github.com/mitsuhiko/flask-oauthhttps://github.com/rmislam/PythonSIFT` didn't work.

I'm not sure if you are still checking these, but if you are I'd REALLY apreaciate any help. 

I will anyway try to implement the method myself, but it'd be nice to have a bar to aim to.

Thank you!

EDIT: Wellp I just found the really dumb error in my comand line (apparently I copied your repositorie's link over something else), which is what I get for doing stuff tired. Still running `pip install git+https://github.com/rmislam/PythonSIFT` installs UNKNOWN, which I'd never seen before, so that's new and weird.

**Comment by Zenos-Paradox** [comment]
I just went through clossed issues and someone had the same problem [here](https://github.com/rmislam/PythonSIFT/issues/15#issue-675742125) (I couldn't figure out how to mention the issue the correct way, sorry). So I'm clossing this.

**Comment by rmislam** [comment]
So sorry! I've come back to this repo and am looking over issues now. Anyway, thanks for your interest in this repo and the kind words!
