### ISSUE TITLE
TypeError: src1 data type = 17 is not supported

### ISSUE THREAD

**Issue by voldenuit-yanagi** [rmislam/PythonSIFT#29]
I got this error at
`dog_images_in_octave.append(subtract(second_image, first_image))` of generateDoGImages(). How should I solve it? Many thanks!

**Comment by rmislam** [comment]
Hi @KurumiKakako , can you please send me the images you are using? Are you just using the images included in this repo? Also, can you please list your python, numpy and cv2 versions?

**Comment by rmislam** [comment]
Hi @voldenuit-yanagi , I haven't heard from you, so I will close this issue. If you can supply me with your images you're using, feel free to reopen this issue.
