### ISSUE TITLE
pysift uses urlparse

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [rmislam/PythonSIFT#35]
Hello, 
Thanks for developing this library ! 

Trying to run it with Python 3, I faced :
```
File lib\site-packages\pysift\api.py:3
-> from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
```

Looking at [this github answer](https://stackoverflow.com/a/48072647/13123667), from `urlparse import urljoin` should be replaced by `from urllib.parse import urljoin`

No time to make a PR sorry, hope that helps still

**Comment by rmislam** [comment]
Hi @TimotheeWrightFicha, thanks for your interest in this repo!

Actually, pysift is someone else's library. This is PythonSIFT. When you pip install pysift, you're actually grabbing someone else's library.

Other people had this issue as well, so you can take a look at my response:
https://github.com/rmislam/PythonSIFT/issues/15#issuecomment-671141165

Let me know if you still run into problems, and feel free to reopen!

**Comment by TimotheeWrightFicha** [comment]
I'm sorry for that then. Cheers
